CREATE TABLE `weather` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`EVENT_ID`	INTEGER NOT NULL,
	`DATETIME`	VARCHAR(20) NOT NULL,
	`TEMP_1`	VARCHAR(10) NULL,
	`TEMP_2`	VARCHAR(10) NULL,
	`JOB_WEATHER`	INTEGER,
	`APP`	VARCHAR(200) NOT NULL
);