CREATE TABLE `FACEBOOK` (
	`PHOTO`	VARCHAR(300) DEFAULT ' ',
	`TOKEN`	VARCHAR(300) NOT NULL,
	`DATETIME` VARCHAR(30) NOT NULL,
	`EXPIRES_IN` VARCHAR(10) NOT NULL,
	`USER_ID` VARCHAR(20) NOT NULL,
	`EMAIL` VARCHAR(100) NOT NULL,
	`APP`	VARCHAR(200) NOT NULL,
	PRIMARY KEY(`USER_ID`)
);