CREATE TABLE `ALARM_MANAGER` (
	`ID`	INTEGER PRIMARY KEY AUTO_INCREMENT,
	`DATETIME`	VARCHAR(25) NULL,
	`DATETIME_DECISION` VARCHAR(25) NOT NULL,
	`JOB_REMINDER` INTEGER NULL,
	`JOB_WEATHER` INTEGER NULL,
	`JOB_CLOSED_EVENT` INTEGER NULL,
	`JOB_DECISION` INTEGER NULL,
	`EVENT_ID` INTEGER NOT NULL,
	`APP`	VARCHAR(200) NOT NULL
);