CREATE TABLE `REQUEST` (
	`ID`	INTEGER,
	`TIMESTAMP`	INTEGER,
	`APP`	VARCHAR(200) NOT NULL,
	PRIMARY KEY(`ID`)
);

CREATE TABLE `SCHEDULES` (
	`REQUEST_ID`	INTEGER,
	`TIMESTAMP`	INTEGER,
	`VOTES`	INTEGER,
	`PRIORITY` INTEGER,
	`APP`	VARCHAR(200) NOT NULL,
	FOREIGN KEY(`REQUEST_ID`) REFERENCES `REQUEST`(`ID`)
);