CREATE TABLE `EVENTS` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`NAME`	VARCHAR(20) NOT NULL,
	`DESCRIPTION`	VARCHAR(140),
	`ACTIVITY`	VARCHAR(20) NOT NULL,
	`TYPE`	INTEGER NOT NULL DEFAULT 0,
	`MAXPPL`	INTEGER NOT NULL,
	`MINPPL`	INTEGER NOT NULL DEFAULT 0,
	`ATMPPL`	INTEGER NOT NULL DEFAULT 1,
	`OWNER`	VARCHAR(20) NOT NULL,
	`APP`	VARCHAR(200) NOT NULL
);

CREATE TABLE `PARTICIPANTS` (
	`PARTICIPANT_ID`	VARCHAR(20) NOT NULL,
	`EVENTS_ID`	INTEGER NOT NULL,
	`APP`	VARCHAR(200) NOT NULL,
	PRIMARY KEY(`PARTICIPANT_ID`,`EVENTS_ID`),
	FOREIGN KEY(`EVENTS_ID`) REFERENCES `EVENTS`(`ID`)
);