CREATE TABLE `GEOLOCATION` (
	`USER_ID`	VARCHAR(20) NOT NULL,
	`LAT`	VARCHAR(15) NOT NULL,
	`LNG`	VARCHAR(15) NOT NULL,
	`DATETIME`	VARCHAR(30) NOT NULL,
	`APP`	VARCHAR(200) NOT NULL,
	PRIMARY KEY(`USER_ID`)
);