CREATE TABLE `EVENTLOCATIONS` (
	`ID`	INTEGER,
	`TIMESTAMP` INTEGER,
	`APP`	VARCHAR(200) NOT NULL,
	PRIMARY KEY(`ID`)
);

CREATE TABLE `VOTING` (
	`LAT`	VARCHAR(30) ,
	`LNG`	VARCHAR(30) ,
	`PRIORITY` INTEGER ,
	`VOTES` INTEGER,
	`EVENTID` INTEGER,
	`CITY` VARCHAR(100),
	`APP`	VARCHAR(200) NOT NULL,
	FOREIGN KEY(`EVENTID`) REFERENCES `EVENTLOCATIONS`(`ID`),
	PRIMARY KEY(`LAT`, `LNG`, `EVENTID`)
);